POST http://localhost:8080/wsec1e1


<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
				  xmlns:gs="http://spring.io/guides/gs-producing-web-service">
   <soapenv:Header/>
   <soapenv:Body>
      <gs:getDiasRequest>
         <gs:name>Jueves</gs:name>
      </gs:getDiasRequest>
   </soapenv:Body>
</soapenv:Envelope>



